# Generated by Django 5.1.4 on 2024-12-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
    ]
