# Generated by Django 5.1.4 on 2024-12-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
